name = "pricetrackr-api"
main = "index.js"
compatibility_date = "2024-01-01"

[observability]
enabled = false
logs = { enabled = true, head_sampling_rate = 1, persist = true, invocation_logs = true }
traces = { enabled = false, persist = true, head_sampling_rate = 1 }

[[kv_namespaces]]
binding = "PRICETRACKR"
id = "a901eb966d144e3081024b10a345b88a"

[[kv_namespaces]]
binding = "USERS"
id = "247e9ac8a5a249a183f7974ff1b2718a"

[vars]
ADMIN_SECRET = "4f2338808548e8e3f4b35ca1c2187e1e"
JWT_SECRET = "f347d250a32906c75a6fd52fd16a3958"

# Note: Set RESEND_API_KEY using: npx wrangler secret put RESEND_API_KEY
